import { Activity, Bot, Cpu, Database, LineChart, ShieldCheck, Sparkles, Zap } from "lucide-react";

const kpis = [{ label: "AI Tasks", value: "12.8K", icon: Cpu }, { label: "Documents", value: "4.2K", icon: Database }, { label: "Automations", value: "326", icon: Zap }, { label: "Trust Score", value: "99.9%", icon: ShieldCheck }];
const activity = ["Revenue agent summarized Q3 pipeline", "Policy document classified as high priority", "Spanish language pack staged", "Weekly BI narrative drafted"];

export default function Dashboard() {
  return <div className="space-y-8">
    <section className="glass relative overflow-hidden rounded-[2rem] p-8 md:p-12"><div className="absolute right-10 top-10 h-36 w-36 rounded-full bg-cyan-400/20 blur-3xl"/><p className="text-sm uppercase tracking-[.4em] text-cyan-300">Genesis Command Center</p><h2 className="mt-4 max-w-4xl text-4xl font-bold md:text-7xl">Operate your business through intelligent agents, trusted data, and automated action.</h2><p className="mt-6 max-w-2xl text-slate-300">A production-ready interface foundation for WolfX BI: no APIs connected yet, designed for Vercel deployment and rapid integration.</p><div className="mt-8 flex flex-wrap gap-3"><button className="rounded-2xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Launch command</button><button className="rounded-2xl border border-white/15 px-5 py-3 text-slate-200">View agent mesh</button></div></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{kpis.map(({label,value,icon:Icon}) => <div key={label} className="glass float rounded-3xl p-6"><Icon className="text-cyan-300"/><p className="mt-8 text-sm text-slate-400">{label}</p><p className="text-3xl font-bold">{value}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="glass rounded-[2rem] p-6"><div className="flex items-center gap-3"><LineChart className="text-emerald-300"/><h3 className="text-2xl font-semibold">Business pulse</h3></div><div className="mt-8 flex h-64 items-end gap-3">{[45,70,52,88,64,92,76,96,81,100].map((h,i)=><div key={i} className="flex-1 rounded-t-2xl bg-gradient-to-t from-cyan-500 to-violet-400" style={{height:`${h}%`}} />)}</div></div><div className="glass rounded-[2rem] p-6"><div className="flex items-center gap-3"><Activity className="text-cyan-300"/><h3 className="text-2xl font-semibold">Live activity</h3></div><div className="mt-6 space-y-4">{activity.map((item)=><div key={item} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">{item}</div>)}</div></div></section>
    <section className="grid gap-4 md:grid-cols-3">{["Strategy Copilot","Document Analyst","Automation Builder"].map((agent)=><div key={agent} className="glass rounded-3xl p-6"><Bot className="text-violet-300"/><h3 className="mt-5 text-xl font-semibold">{agent}</h3><p className="mt-2 text-sm text-slate-400">Agent widget prepared with mocked state, status, and handoff-ready layout.</p><Sparkles className="mt-8 text-cyan-300"/></div>)}</section>
  </div>;
}
